#!/usr/bin/env python3

import sys

def factorize(number):
    # Find the first factor
    for i in range(2, number):
        if number % i == 0:
            return i, number // i

    # If no factors found, the number is prime
    return number, 1

def factorize_file(filename):
    with open(filename, 'r') as file:
        for line in file:
            number = int(line.strip())
            p, q = factorize(number)
            print(f"{number}={p}*{q}")

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    filename = sys.argv[1]
    factorize_file(filename)
